CREATE DATABASE Humanresource;
USE Humanresource

CREATE TABLE EMPLOYEE (
    EmpNo varchar(50),
    Ename VARCHAR(50),
    Job VARCHAR(50),
    Salary DECIMAL(10,2),
    DeptNo INT
);

INSERT INTO EMPLOYEE VALUES
('E001', 'Null', 'Clerk', 40000, 20),
('E002', 'Agaba', 'Manager', 16000, 30),
('E003', 'Mary', 'SalesLady', 20000, 20),
('E004', 'Timo', 'Clerk', 40000, 30),
('E005', 'Simon', 'Manager', 60000, 40),
('E006', 'Mark', 'Manager', 45000, 10),
('E007', 'Solomon', 'Teacher', 30000, 30);

SELECT * FROM EMPLOYEE;

--a)
CREATE VIEW VIEW_A AS SELECT * FROM EMPLOYEE WHERE Ename LIKE 'S%';
SELECT * FROM VIEW_A;

--B)
CREATE VIEW VIEW_B AS SELECT * FROM EMPLOYEE WHERE DeptNo NOT IN (20);
SELECT * FROM VIEW_B;

--C) EMPLOYEES HAVING SALARIES IN RANGE O 40000 to 60000
CREATE VIEW VIEW_C AS SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 40000 AND 60000;
SELECT * FROM VIEW_C;

--D)
CREATE VIEW VIEW_D AS SELECT COUNT(EmpNo) AS NumberOfManagers, SUM(Salary) AS TotalSpentOnManagers, MAX(Salary) AS HighestPaidManager FROM EMPLOYEE WHERE Job = 'Manager';
SELECT * FROM VIEW_D;

--E)
CREATE VIEW VIEW_E AS SELECT Ename, Job FROM EMPLOYEE ORDER BY EmpNo DESC LIMIT 2;
SELECT * FROM VIEW_E;

--F) VIEW F
CREATE VIEW VIEW_F AS SELECT Job, Salary FROM EMPLOYEE ORDER BY Job ASC, Salary DESC;
SELECT * FROM VIEW_F;

--G) EMPLOYEES SALARY > 40000
CREATE VIEW VIEW_G AS SELECT * FROM EMPLOYEE WHERE Salary > 40000;
SELECT * FROM VIEW_G;

--H) CUOLUMN SIZE CHANGE 4 ENAME 
ALTER TABLE EMPLOYEE MODIFY Ename VARCHAR(40);
SELECT * FROM EMPLOYEE;

--I) ADDING A NEW COLUMN CALLED RESIDENCE
ALTER TABLE EMPLOYEE ADD Residence VARCHAR(50);
SELECT * FROM EMPLOYEE;

--J)
INSERT INTO EMPLOYEE (EmpNo, Ename, Job) VALUES ('E0010', 'Jane', 'Teacher');
SELECT * FROM EMPLOYEE;

--K)MODIFICATION
UPDATE EMPLOYEE SET Job = 'Engineer', Salary = Salary * 1.10 WHERE EmpNo = 'E004';
SELECT * FROM EMPLOYEE;

--L) ELIMINATE THE LAST ROW FROM THE EMPLOYEE TABLE
DELETE FROM EMPLOYEE WHERE EmpNo = 'E0010';
SELECT * FROM EMPLOYEE;

--M)
CREATE TABLE MEAL_SERVICE(
    DeptNo INT,
    Meal VARCHAR(50),
    Drink VARCHAR(50)
);

INSERT INTO MEAL_SERVICE VALUES
(20, 'Rice', 'Soda'),
(30, 'Beans', 'Water'),
(40, 'Ugali', 'Juice');


--n)append a foreign key on this table using DeptNo as the primary key from the EMPLOYEE table
ALTER TABLE MEAL_SERVICE ADD CONSTRAINT FK_DeptNo FOREIGN KEY (DeptNo) REFERENCES EMPLOYEE(DeptNo);







